keys:
  - &primary age1305grxl649knx87u3vlyx39huk09vnwej8njgndwh7kqv4ysgddqmrl0eg
  - &nightman age10kfqxyaeh98j9dzsarj0k3yjvve5qz6qcd9pgxsq8k5fdm0m4f0s7gfgcq
  - &dayman age1pegrsqng4jvq5wrgrkhcr8ukzskw0sajw580zvmcplztx2zrjuls0kynkq
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *primary
      - *nightman
      - *dayman
